# Generated by Django 4.2.7 on 2023-12-01 14:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("userId", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=100, unique=True)),
                (
                    "password",
                    models.CharField(
                        default="",
                        max_length=100,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[a-zA-Z0-9]*$",
                                "Only alphanumeric characters are allowed.",
                            )
                        ],
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("dateJoined", models.DateField(auto_now_add=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("STUDENT", "Student"),
                            ("TUTOR", "Tutor"),
                            ("ADMIN", "Administrator"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
            options={
                "db_table": "User",
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                ("courseId", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("enrollmentCapacity", models.IntegerField()),
                (
                    "tutor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tutor_portal.user",
                    ),
                ),
            ],
            options={
                "db_table": "Course",
            },
        ),
    ]
