# Generated by Django 4.2.7 on 2023-12-01 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tutor_portal", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Material",
            fields=[
                ("materialId", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=100)),
                ("content", models.TextField()),
                ("uploadDate", models.DateField(auto_now_add=True)),
                ("documentType", models.CharField(max_length=50)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tutor_portal.course",
                    ),
                ),
            ],
            options={
                "db_table": "Material",
            },
        ),
    ]
