# Generated by Django 4.2.7 on 2023-12-05 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor_portal', '0002_material'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='course',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Material',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
