# Generated by Django 4.2.7 on 2023-12-06 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor_portal', '0003_assignment_submission_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterModelTable(
            name='assignment',
            table=None,
        ),
        migrations.AlterModelTable(
            name='course',
            table=None,
        ),
        migrations.AlterModelTable(
            name='grade',
            table=None,
        ),
        migrations.AlterModelTable(
            name='material',
            table=None,
        ),
        migrations.AlterModelTable(
            name='submission',
            table=None,
        ),
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
