# Generated by Django 4.2.7 on 2023-12-06 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tutor_portal", "0004_alter_user_password_alter_assignment_table_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebRTCSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.CharField(max_length=100, unique=True)),
                ("sdp", models.TextField(blank=True, null=True)),
                ("ice_candidates", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tutor_portal.user",
                    ),
                ),
            ],
        ),
    ]
