# Generated by Django 4.2.7 on 2023-12-06 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tutor_portal", "0005_webrtcsession"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_banned",
            field=models.BooleanField(default=False),
        ),
    ]
