# Generated by Django 4.2.7 on 2023-12-09 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tutor_portal", "0007_reportedincident"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="tutor",
        ),
        migrations.RemoveField(
            model_name="grade",
            name="assignment",
        ),
        migrations.RemoveField(
            model_name="grade",
            name="student",
        ),
        migrations.RemoveField(
            model_name="material",
            name="course",
        ),
        migrations.RemoveField(
            model_name="reportedincident",
            name="reported_user",
        ),
        migrations.RemoveField(
            model_name="reportedincident",
            name="reporter",
        ),
        migrations.RemoveField(
            model_name="submission",
            name="assignment",
        ),
        migrations.RemoveField(
            model_name="submission",
            name="student",
        ),
        migrations.RemoveField(
            model_name="webrtcsession",
            name="user",
        ),
        migrations.DeleteModel(
            name="Assignment",
        ),
        migrations.DeleteModel(
            name="Course",
        ),
        migrations.DeleteModel(
            name="Grade",
        ),
        migrations.DeleteModel(
            name="Material",
        ),
        migrations.DeleteModel(
            name="ReportedIncident",
        ),
        migrations.DeleteModel(
            name="Submission",
        ),
        migrations.DeleteModel(
            name="User",
        ),
        migrations.DeleteModel(
            name="WebRTCSession",
        ),
    ]
